Repository gardener/ci-infra, pull requests merged in 2022-04, with the labels that each got.

#154 Update nginx to v1.1.2
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#157 Enable tests and checks for shoot-oidc-service repository
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#113 Add api diff job
  config/jobs/gardener/gardener-apidiff.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#162 Minor nit in apidiff job
  config/jobs/gardener/gardener-apidiff.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#163 Remove ci-infra build github workflow
  .github/workflows/build-ci-infra-images.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#164 Update golang-test images
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
  config/jobs/gardener/gardener-apidiff.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#178 Restrict approve and lgtm to OWNERS for the whole org
  config/prow/plugins.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#167 Disable parallel builds / don't build ci-infra images on config changes
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/ci-infra/build-golang-test-image.yaml
  config/jobs/gardener/build-gardener-images.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#184 Increase memory limits for gardener integration tests
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#185 remove duplicated autobump config for eu.gcr.io/gardener-project/ci-infra
  config/prow/autobump-config/prow-component-autobump-config.yaml
  config/prow/autobump-config/prow-job-autobump-config.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#190 Add option to inject EFFECTIVE_VERSION build-arg
  prow/cmd/image-builder/buildcontroller.go
  prow/cmd/image-builder/buildcontroller_test.go
  prow/cmd/image-builder/main.go
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#188 Add e2e tests for shoot-oidc-service pull requests
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-e2e-kind.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#192 Drop obsolete kind installation in gardener-e2e-kind
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/release/gardener-e2e-kind-release.yaml
Labels: kind/cleanup, size/S, approved, lgtm, cla: yes

#194 Fix deployer permissions
  config/prow/cluster/bootstrap-trusted/trusted_serviceaccounts.yaml
  config/prow/deploy.sh
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#199 Revert "Update Prow to v20220418-9a5c901fc3"
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/mkpj.sh
  config/prow/cluster/cherrypicker_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/needs-rebase_deployment.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
  hack/bootstrap-config.sh
  hack/check-config.sh
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#202 Add periodic job for oidc service
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-e2e-kind.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#208 Update to golang-1.17.9
  Makefile
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/ci-infra/build-golang-test-image.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
  config/jobs/gardener/gardener-apidiff.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#210 Do not inject-effective-version in ci-infra build jobs
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/ci-infra/build-golang-test-image.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#213 Null routing for KubeAggregatedAPIErrors
  config/prow/cluster/monitoring/base-prow/alertmanager/config.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#216 Switch deck to GitHub Apps Auth
  config/prow/cluster/deck_deployment.yaml
Labels: kind/cleanup, size/S, approved, lgtm, cla: yes

#212 Allow deployer creating daemonsets and podmonitors
  config/prow/cluster/bootstrap-trusted/trusted_serviceaccounts.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#214 Change default for inject-effective-version to false
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-test-builds.yaml
  config/jobs/gardener/release/gardener-build-dev-images-release.yaml
  config/jobs/gardener/release/gardener-test-builds-release.yaml
  prow/cmd/image-builder/main.go
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#217 Use latest grafana version with an Apache2.0 license
  config/prow/cluster/monitoring/base-prow/kustomization.yaml
Labels: kind/cleanup, size/XS, approved, lgtm, cla: yes
