Repository gardener/ci-infra, pull requests merged in 2022-08, with the labels that each got.

#332 Update shoot manifests with new route53 users
  config/clusters/shoot-workload.yaml
  config/clusters/shoot.yaml
Labels: kind/enhancement, approved, ok-to-test, lgtm, cla: yes

#337 Revert "Update Prow to v20220805-b020793770"
  config/jobs/ci-infra/ci-infra-automate-testgrid.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/mkpj.sh
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/needs-rebase_deployment.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
  hack/bootstrap-config.sh
  hack/check-config.sh
  hack/check-testgrid-config.sh
Labels: size/M, approved, lgtm, cla: yes

#339 Revert "Update Prow to v20220805-b020793770"
  config/jobs/ci-infra/ci-infra-automate-testgrid.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/mkpj.sh
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/needs-rebase_deployment.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
  hack/bootstrap-config.sh
  hack/check-config.sh
  hack/check-testgrid-config.sh
Labels: size/M, approved, lgtm, cla: yes

#345 Update oidc test image to go 1.18
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
Labels: kind/task, size/XS, approved, lgtm, cla: yes

#347 Update golang test images
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#348 Update alpine image to 3.16.2
  Dockerfile
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#353 Cleanup old gardener release branch jobs
  config/jobs/gardener/release/gardener-e2e-kind-migration-release.yaml
  config/jobs/gardener/release/gardener-e2e-kind-release.yaml
Labels: kind/cleanup, size/L, approved, lgtm, cla: yes

#355 Ask contributors to report flakes in test reports
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#351 Switch gardener jobs to go1.19
  config/jobs/gardener/gardener-apidiff.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
Labels: kind/task, size/S, approved, lgtm, cla: yes

#359 Enforce push access for gardener-prow github app in branchprotector
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/prow/config.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#365 Promote `*-gardener-e2e-kind-migration` to required
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/release/gardener-e2e-kind-migration-release.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#368 Increase CPU limits of kube-state-metrics
  config/prow/cluster/monitoring/base-prow/kubeStateMetrics-deployment.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes
