Repository gardener/ci-infra, pull requests merged in 2022-06, with the labels that each got.

#266 Update to go 1.17.11 and 1.18.3
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#267 Update kubectl image to v1.22.10
  config/jobs/ci-infra/ci-infra-postsubmits.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#269 Fix/nginx deployment permissions
  config/prow/cluster/bootstrap-trusted/kustomization.yaml
  config/prow/cluster/bootstrap-trusted/trusted_serviceaccounts.yaml
  hack/bootstrap-config.sh
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#272 Disable `lgtm_acts_as_approve` for ci-infra
  config/prow/plugins.yaml
Labels: kind/cleanup, size/XS, approved, lgtm, cla: yes

#275 Update shoot spec
  config/clusters/shoot-workload.yaml
  config/clusters/shoot.yaml
Labels: kind/task, size/S, approved, lgtm, cla: yes

#276 Increase CPU limits
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
  config/prow/cluster/monitoring/base-prow/nodeExporter-daemonset.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#278 Enhance highlight regexes
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#280 Highlight standard ginkgo error from e2e tests
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#292 Use ci-infra cherrypicker
  config/prow/cluster/cherrypicker_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#257 Enable testgrid for gardener prow
  README.md
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/ci-infra/build-golang-test-image.yaml
  config/jobs/ci-infra/ci-infra-automate-testgrid.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-postsubmits.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-e2e-kind.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-build-dev-images-release.yaml
  config/jobs/gardener/release/gardener-e2e-kind-release.yaml
  config/jobs/gardener/release/gardener-integration-tests-release-previous-golang.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release-previous-golang.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
  config/prow/autobump-config/prow-component-autobump-config.yaml
  config/prow/config.yaml
  config/testgrids/config.yaml
  config/testgrids/default.yaml
  hack/check-testgrid-config.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#294 Remove world-readable flag from upload testgrid job
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/ci-infra/ci-infra-automate-testgrid.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#293 Add git to cherrypicker image
  Dockerfile
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#297 Revert "Update Prow to v20220623-3ef0bc3b81"
  config/jobs/ci-infra/ci-infra-automate-testgrid.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/mkpj.sh
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/needs-rebase_deployment.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
  hack/bootstrap-config.sh
  hack/check-config.sh
  hack/check-testgrid-config.sh
Labels: kind/regression, size/M, approved, lgtm, cla: yes
