Repository gardener/ci-infra, pull requests merged in 2022-02, with the labels that each got.

#77 Add org to triage robot queries
  config/jobs/common/issue-pr-lifecycle.yaml
  config/prow/cluster/monitoring/grafana/dashboards/ghproxy.json
  config/prow/cluster/monitoring/grafana/dashboards/tide.json
Labels: kind/bug, size/M, approved, lgtm

#78 Notify oliver-goetz for critical alerts
  config/prow/cluster/monitoring/alertmanager/config.yaml
Labels: area/monitoring, kind/enhancement, size/XS, approved, lgtm

#79 Set triage robot to dry-run
  config/jobs/common/issue-pr-lifecycle.yaml
Labels: kind/bug, size/XS, approved, lgtm

#80 Deactivate rate limit alerts
  config/jobs/common/issue-pr-lifecycle.yaml
  config/prow/cluster/monitoring/prow_prometheusrule.yaml
Labels: kind/bug, size/M, approved, lgtm

#83 Fix token path in cla triage job
  config/jobs/common/cla-assistant.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#88 Fix pre-submit-test for developments
  Makefile
  config/jobs/ci-infra/ci-infra-presubmits.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#87 Introduce periodic check of CLA labels
  Dockerfile
  Makefile
  VERSION
  config/jobs/common/cla-assistant.yaml
  config/prow/cluster/cla_assistant_deployment.yaml
  prow/external-plugins/cla-assistant/main.go
  prow/external-plugins/cla-assistant/plugin.go
  prow/external-plugins/cla-assistant/plugin_test.go
Labels: kind/bug, size/L, approved, lgtm, cla: yes

#93 Move periodic check for cla status from prow job into cla-assistant plugin
  config/jobs/common/cla-assistant.yaml
  prow/external-plugins/cla-assistant/plugin.go
  prow/external-plugins/cla-assistant/plugin_test.go
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#100 Fix prow job entrypoints
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes
