Repository gardener/ci-infra, pull requests merged in 2022-11, with the labels that each got.

#468 Update kaniko to v1.9.1
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-test-builds.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-test-builds.yaml
  config/jobs/gardener/gardener-test-builds.yaml
  config/jobs/gardener/release/gardener-test-builds-release.yaml
  prow/cmd/image-builder/main.go
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#464 Update go images to 1.18.8 and 1.19.3
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#470 Update kubectl image to v1.24.7
  config/jobs/ci-infra/ci-infra-postsubmits.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#471 Update nginx to v1.4.0
  config/prow/cluster/bootstrap-trusted/trusted_serviceaccounts.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
  config/prow/deploy.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#472 Update grafana to v7.5.17
  config/prow/cluster/monitoring/base-prow/kustomization.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#462 Deactivate Release Milestone Check for gardener v1.59 and prepare Milestone for next release
  config/prow/config.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#467 Activate job-forker for gardener/gardener
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-node.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-test-builds.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#475 Fix job-forker email / align `labels-override` cli argument with other apps
  config/jobs/ci-infra/ci-infra-periodics.yaml
  prow/cmd/job-forker/main.go
  prow/pkg/githubinteractor/github.go
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#477 Allow job-forker to configure its email used for git explicitly
  config/jobs/ci-infra/ci-infra-periodics.yaml
  prow/cmd/job-forker/main.go
  prow/pkg/git/fakegit/fakegitclient.go
  prow/pkg/githubinteractor/github.go
Labels: kind/bug, size/L, approved, lgtm, cla: yes

#366 Deflake cherrypicker tests
  go.mod
  prow/external-plugins/cherrypicker/README.md
  prow/external-plugins/cherrypicker/main.go
  prow/external-plugins/cherrypicker/server.go
  prow/external-plugins/cherrypicker/server_test.go
Labels: kind/flake, size/L, approved, lgtm, cla: yes

#480 Adapt gardener/gardener HA jobs
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#484 Allow collaborators to trigger things
  config/prow/plugins.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#487 Increase cpu limit of kube-rbac-proxy-main in kube-state-metrics deployment
  config/prow/cluster/monitoring/base-prow/kubeStateMetrics-deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#490 Add release milestone check for gardener release v1.60 to tide
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#495 Deactivate Release Milestone Check for gardener v1.60
  config/prow/config.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#499 Fix determination of open PRs in job-forker
  prow/pkg/githubinteractor/github.go
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#493 introduced prow job to run KIND e2e tests for DWD
  config/jobs/dependency-watchdog/dependency-watchdog-e2e-kind.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#489 Build `gardener-operator` images and execute its e2e tests
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-test-builds.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#503 Updating HA Prow jobs from optional to required
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#504 Drop `gardener-seed-admission-controller`
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-test-builds.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#508 Add release milestone check for gardener release v1.61 to tide
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes
