Repository gardener/ci-infra, pull requests merged in 2022-01, with the labels that each got.

#29 Add basic monitoring
  README.md
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/ci-infra/echo-test.yaml
  config/prow/cluster/monitoring/alertmanager/config.yaml
  config/prow/cluster/monitoring/alertmanager/slack-messages.tmpl
  config/prow/cluster/monitoring/alertmanager_rbac.yaml
  config/prow/cluster/monitoring/alertmanager_service.yaml
  config/prow/cluster/monitoring/blackbox-exporter_configmap.yaml
  config/prow/cluster/monitoring/blackbox-exporter_deployment.yaml
  config/prow/cluster/monitoring/blackbox-exporter_service.yaml
  config/prow/cluster/monitoring/grafana/dashboard-sources.yaml
  config/prow/cluster/monitoring/grafana/dashboards/deck.json
  config/prow/cluster/monitoring/grafana/dashboards/ghproxy.json
  config/prow/cluster/monitoring/grafana/dashboards/hook.json
  config/prow/cluster/monitoring/grafana/dashboards/plank.json
  config/prow/cluster/monitoring/grafana/dashboards/prow.json
  config/prow/cluster/monitoring/grafana/dashboards/sinker.json
  config/prow/cluster/monitoring/grafana/dashboards/slo.json
  config/prow/cluster/monitoring/grafana/dashboards/tide.json
  config/prow/cluster/monitoring/grafana/datasources.yaml
  config/prow/cluster/monitoring/grafana/grafana.ini
  config/prow/cluster/monitoring/grafana_deployment.yaml
  config/prow/cluster/monitoring/grafana_rbac.yaml
  config/prow/cluster/monitoring/grafana_service.yaml
  config/prow/cluster/monitoring/kube-state-metrics_deployment.yaml
  config/prow/cluster/monitoring/kube-state-metrics_rbac.yaml
  config/prow/cluster/monitoring/kube-state-metrics_service.yaml
  config/prow/cluster/monitoring/kube-state-metrics_servicemonitor.yaml
  config/prow/cluster/monitoring/kustomization.yaml
  config/prow/cluster/monitoring/monitoring_ingress.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/README.md
  config/prow/cluster/monitoring/prometheus-operator-crds/kustomization.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_alertmanagerconfigs.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_alertmanagers.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_podmonitors.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_probes.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_prometheuses.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_prometheusrules.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_servicemonitors.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_thanosrulers.yaml
  config/prow/cluster/monitoring/prometheus-operator-crds/update-crds.sh
  config/prow/cluster/monitoring/prometheus/additional-scrape-targets.yaml
  config/prow/cluster/monitoring/prometheus_operator_deployment.yaml
  config/prow/cluster/monitoring/prometheus_operator_rbac.yaml
  config/prow/cluster/monitoring/prometheus_rbac.yaml
  config/prow/cluster/monitoring/prometheus_service.yaml
  config/prow/cluster/monitoring/prow-monitoring_namespace.yaml
  config/prow/cluster/monitoring/prow_alertmanager.yaml
  config/prow/cluster/monitoring/prow_prometheus.yaml
  config/prow/cluster/monitoring/prow_prometheusrule.yaml
  config/prow/cluster/monitoring/prow_servicemonitors.yaml
  config/prow/cluster/prow_ingress.yaml
  config/prow/config.yaml
  config/prow/deploy.sh
Labels: area/monitoring, kind/enhancement, size/XXL, approved, lgtm

#30 Fix deployer RBAC permissions for monitoring components
  config/prow/cluster/trusted_serviceaccounts.yaml
Labels: kind/bug, size/S, approved, lgtm

#35 Add oliver-goetz as reviewer and approver
  OWNERS_ALIASES
Labels: kind/enhancement, size/XS, approved, lgtm

#38 Extend .gitignore
  .gitignore
Labels: kind/enhancement, size/S, approved, lgtm

#40 Deploy ingress-nginx controller
  config/clusters/shoot-workload.yaml
  config/clusters/shoot.yaml
  config/prow/cluster/ingress-nginx/00_ingress-nginx-namespace.yaml
  config/prow/cluster/ingress-nginx/helm/README.md
  config/prow/cluster/ingress-nginx/helm/generate-ingress-nginx-deployments.sh
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
  config/prow/cluster/trusted_serviceaccounts.yaml
  config/prow/deploy.sh
Labels: kind/enhancement, size/XXL, approved, lgtm

#45 Simplify prow trusted cluster setup
  config/clusters/shoot-workload.yaml
  config/clusters/shoot.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
  config/prow/cluster/monitoring/prow_alertmanager.yaml
  config/prow/cluster/monitoring/prow_prometheus.yaml
Labels: kind/enhancement, size/L, approved, lgtm

#46 Update github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/pull_request_template.md
Labels: kind/enhancement, size/M, approved, lgtm

#47 Provide a rolling update strategy for ghproxy
  config/prow/cluster/ghproxy_deployment.yaml
Labels: kind/bug, size/XS, approved, lgtm

#50 Autodeploy updates for prow and prow jobs
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm

#56 Add gcsweb deployment
  config/prow/cluster/gcsweb_deployment.yaml
  config/prow/cluster/gcsweb_ingress.yaml
  config/prow/cluster/gcsweb_namespace.yaml
  config/prow/cluster/gcsweb_service.yaml
  config/prow/config.yaml
  config/prow/deploy.sh
Labels: kind/enhancement, size/L, approved, lgtm
