Repository gardener/ci-infra, pull requests merged in 2022-05, with the labels that each got.

#224 Use golang-test:1.17-...
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
  config/jobs/gardener/gardener-apidiff.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#228 Use golang-test:1.17-...again
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
  config/jobs/gardener/gardener-apidiff.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
  prow/cmd/image-builder/buildcontroller.go
  prow/cmd/image-builder/main.go
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#233 Null route for KubeAggregatedAPIDown errors
  config/prow/cluster/monitoring/base-prow/alertmanager/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#231 Test gardener/gardener master branch with Go 1.18 image
  config/jobs/gardener/gardener-apidiff.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#237 Add a prow job to verify ci-infra builds
  config/jobs/ci-infra/ci-infra-presubmits.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#236 Correct command help URL in welcome message
  config/prow/plugins.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#241 Make buildlog highlighting more helpful
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#245 Null routing for KubeCPUOvercommit and KubeClientCertificateExpiration alerts
  config/prow/cluster/monitoring/base-prow/alertmanager/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#249 Cleanup old labels added by gardener-robot
  config/prow/labels.yaml
Labels: kind/cleanup, size/L, approved, lgtm, cla: yes

#246 Update golang versions
  Dockerfile
  Makefile
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  images/golang-test/Dockerfile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes
