Repository gardener/ci-infra, pull requests merged in 2022-03, with the labels that each got.

#120 Enable unit and integration tests for gardener repository
  Dockerfile
  Makefile
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-pull-tests.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#118 Upgrade to golang 1.17.7
  Dockerfile
  config/jobs/ci-infra/ci-infra-presubmits.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#117 Prow housekeeping with small enhancements
  config/clusters/shoot-workload.yaml
  config/clusters/shoot.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/prow/cluster/bootstrap-trusted/trusted_serviceaccounts.yaml
  config/prow/deploy.sh
  hack/bootstrap-config.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#122 Improve scheduling of test jobs
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-pull-tests.yaml
  config/jobs/gardener/gardener-tests.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#123 do not build images when only configuration files are changing in ci-infra
  .github/workflows/build-ci-infra-images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#138 Update to golang-1.17.8
  Dockerfile
  Makefile
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/gardener/gardener-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#139 Enable tests for release branches of gardener/gardener
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-e2e-kind-release.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#141 Test job improvements
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-e2e-kind-release.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#143 Always run gardener/gardener presubmit test jobs
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/release/gardener-e2e-kind-release.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#136 Reactivate ghproxy token alerting
  config/prow/cluster/monitoring/grafana/dashboards/ghproxy.json
  config/prow/cluster/monitoring/prow_prometheusrule.yaml
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#144 Enable prow in gardener/gardener
  config/jobs/common/issue-pr-lifecycle.yaml
  config/prow/cluster/cherrypicker_deployment.yaml
  config/prow/cluster/cherrypicker_service.yaml
  config/prow/config.yaml
  config/prow/deploy.sh
  config/prow/labels.yaml
  config/prow/plugins.yaml
Labels: kind/enhancement, size/XXL, approved, lgtm, cla: yes

#148 Only include desired branches in protection
  config/prow/config.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#150 Allow concourse to push release commits
  config/prow/config.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#151 Fix protection restriction
  config/prow/config.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#149 Run release tests on release branches only
  config/jobs/gardener/release/gardener-e2e-kind-release.yaml
  config/jobs/gardener/release/gardener-integration-tests-release.yaml
  config/jobs/gardener/release/gardener-unit-tests-release.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#153 gardener branding
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/webserver-static-files/gardener-favicon.png
  config/prow/cluster/webserver-static-files/gardener-large.png
  config/prow/cluster/webserver-static-files/gardener.svg
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#155 Fix settings for concourse (3)
  config/jobs/common/issue-pr-lifecycle.yaml
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes
