Repository gardener/ci-infra, pull requests merged in 2022-09, with the labels that each got.

#371 Update nginx to v1.3.0
  config/prow/cluster/ingress-nginx/helm/generate-ingress-nginx-deployments.sh
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#375 Fix deployer permissions
  config/prow/cluster/bootstrap-trusted/trusted_serviceaccounts.yaml
Labels: kind/bug, size/L, approved, lgtm, cla: yes

#374 Fix grafana network policy
  config/prow/cluster/monitoring/base-prow/grafana-networkPolicy.yaml
  config/prow/cluster/monitoring/base-prow/kustomization.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#377 Route InfoInhibitor alert to null-receiver
  config/prow/cluster/monitoring/base-prow/alertmanager/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#380 Increase cpu limit of kube-rbac-proxy in prometheus-operator
  config/prow/cluster/monitoring/base-prow/kustomization.yaml
  config/prow/cluster/monitoring/base-prow/prometheusOperator-deployment.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#383 Remove Milestone check from required statuses
  config/prow/config.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#381 Add release milestone check for gardener release v1.55 to tide
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#385 Deactivate Release Milestone Check for gardener v1.55 and prepare Milestone for next release
  config/prow/config.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#387 Update to golang 1.18.6 & 1.19.1
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#287 Create a script for rotating secrets
  README.md
  config/kubeconfig/garden.yaml
  config/kubeconfig/kubeconfig--gardener--prow-combined.yaml
  hack/rotate-secrets.sh
  hack/setup-prow-kubeconfig.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#392 Add govulncheck to CI for g/g repo
  config/jobs/gardener/gardener-check-vulnerabilities.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#405 Deactivate Release Milestone Check for gardener `v1.56`
  config/prow/config.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#415 Fix label-sync job
  config/jobs/ci-infra/ci-infra-periodics.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes
