Repository gardener/ci-infra, pull requests merged in 2022-12, with the labels that each got.

#511 Deactivate Release Milestone Check for gardener v1.61
  config/prow/config.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#513 Merge job-forker PRs automatically
  config/jobs/ci-infra/ci-infra-periodics.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#514 Drop remaining optional settings for single-zone jobs
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-61.yaml
Labels: kind/cleanup, size/XS, approved, lgtm, cla: yes

#521 Activate release milestone for gardener v1.62
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#518 Update go images to 1.18.9 and 1.19.4
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#520 Check tree hash before removing lgtm label
  config/prow/plugins.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#510 Add E2E Gardener upgrade test Prow jobs
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#525 Deactivate Release Milestone Check for gardener v1.62 and prepare Milestone for next release
  config/prow/config.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#527 Adjust CPU and memory requests of test jobs
  config/jobs/dependency-watchdog/dependency-watchdog-e2e-kind.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-e2e-kind.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-60.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-61.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-62.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#531 Increase cpu and memory requests of certain test jobs again
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-60.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-61.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-62.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#528 Bind prometheus pods to system-component nodes
  config/prow/cluster/monitoring/base-prow/alertmanager-alertmanager.yaml
  config/prow/cluster/monitoring/base-prow/blackboxExporter-deployment.yaml
  config/prow/cluster/monitoring/base-prow/grafana-deployment.yaml
  config/prow/cluster/monitoring/base-prow/kubeStateMetrics-deployment.yaml
  config/prow/cluster/monitoring/base-prow/kustomization.yaml
  config/prow/cluster/monitoring/base-prow/prometheus.yaml
  config/prow/cluster/monitoring/base-prow/prometheusAdapter-deployment.yaml
  config/prow/cluster/monitoring/base-prow/prometheusOperator-deployment.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#529 Update nginx to v1.5.1
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes
