Repository gardener/ci-infra, pull requests merged in 2022-10, with the labels that each got.

#419 Add release milestone check for gardener release v1.57 to tide
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#421 Fix release milestone check for gardener/gardener
  config/prow/config.yaml
Labels: kind/regression, size/S, approved, lgtm, cla: yes

#417 Add prow jobs for gardener-extension-registry-cache repo
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-build-images.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-test-builds.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
  config/testgrids/config.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#423 Change registry-cache build targets
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-build-images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#425 Deactivate Release Milestone Check for gardener v1.57
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#429 Update go images to 1.18.7 and 1.19.2
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#435 added prow jobs for dependency-watchdog
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-build-dev-images.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-check-vulnerabilities.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-test-builds.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-unit-tests.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  config/testgrids/config.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#442 Increase memory request of e2e tests
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-e2e-kind.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#446 Add release milestone check for gardener release v1.58 to tide
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#443 Add gardener-core team memeber to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#441 Changes from prow cluster migration
  README.md
  config/clusters/shoot-workload.yaml
  config/clusters/shoot.yaml
  config/prow/cluster/monitoring/base-prow/prometheus.yaml
  config/prow/cluster/monitoring/trusted-cluster/kustomization.yaml
  config/prow/cluster/monitoring/trusted-cluster/prometheus.yaml
  hack/rotate-secrets.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#450 Deactivate Release Milestone Check for gardener v1.58 and prepare Milestone for next release
  config/prow/config.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#455 Update golangci to v1.50.1
  .golangci.yaml
  hack/tools.mk
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#459 Reduce memory request of HA e2e tests
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#460 Check for `needs-rebase` every hour
  config/prow/cluster/needs-rebase_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#456 Adapt `gardener/gardener` HA test jobs
  config/jobs/gardener/gardener-e2e-kind-ha-node.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-zone.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#457 Add release milestone check for gardener release v1.59 to tide
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes
