Repository gardener/ci-infra, pull requests merged in 2023-11, with the labels that each got.

#983 Decrease volume size of `ghproxy`
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/ghproxy_pvc.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#990 Copy alpine:3.18.4
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1004 Cleanup obsolete hack scripts
  hack/rotate-secrets.sh
  hack/setup-prow-kubeconfig.sh
Labels: kind/cleanup, size/L, approved, lgtm, cla: yes

#1015 Deploy and enable `athens` as `GOPROXY` on trusted and build clusters
  config/prow/cluster/athens/athens-proxy.yaml
  config/prow/cluster/athens/athens_deployment.yaml
  config/prow/cluster/athens/athens_namespace.yaml
  config/prow/cluster/athens/athens_prometheus_rbac.yaml
  config/prow/cluster/athens/helm/README.md
  config/prow/cluster/athens/helm/generate-athens-deployments.sh
  config/prow/cluster/athens/helm/values.yaml
  config/prow/cluster/athens/kustomization.yaml
  config/prow/config.yaml
  config/prow/deploy.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#1018 Update resource requests of `athens`
  config/prow/cluster/athens/athens_deployment.yaml
  config/prow/cluster/athens/helm/values.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1019 [cherry-picker] Support copying multiple release-notes to cherry-picked PR
  prow/external-plugins/cherrypicker/server.go
  prow/external-plugins/cherrypicker/server_test.go
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#1028 Revert version of `gcsweb`
  config/prow/cluster/gcsweb_deployment.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#1026 Deploy `athens` in an HA configuration
  config/prow/cluster/athens/athens-proxy.yaml
  config/prow/cluster/athens/athens_deployment.yaml
  config/prow/cluster/athens/helm/values.yaml
  config/prow/cluster/athens/kustomization.yaml
  config/prow/cluster/athens/patch-athens-proxy.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#1030 Fix kustomize for `ingress-nginx`
  config/prow/cluster/ingress-nginx/kustomization.yaml
  config/prow/cluster/ingress-nginx/patch-admission-webhook-jobs.yaml
  config/prow/cluster/ingress-nginx/patch-ingress-nginx-admission-create.yaml
  config/prow/cluster/ingress-nginx/patch-ingress-nginx-admission-patch.yaml
Labels: kind/regression, size/M, approved, lgtm, cla: yes
