Repository gardener/ci-infra, pull requests merged in 2023-01, with the labels that each got.

#536 Fixed prow job `ci-gardener-e2e-kind-upgrade`
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-62.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#546 Update to Go 1.18.10 and 1.19.5
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: area/security, kind/enhancement, size/S, approved, lgtm, cla: yes

#532 Adapt build of gardener-extension-registry-cache for concourse release jobs
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-build-images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#554 Add release milestone check for gardener release v1.63 to tide
  config/prow/config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#555 Grant push access to `ci` team and use merge method squash for `gardener/gardener-extension-registry-cache`
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#556 Allow concourse to create release commit for the registry-cache extension
  config/prow/config.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes
