Repository gardener/ci-infra, pull requests merged in 2023-12, with the labels that each got.

#1031 Use `athens` as `GOPROXY` for image builds in `gardener/gardener` and `gardener/ci-infra`
  Dockerfile
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-test-builds.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1037 Add job to build `shoot-rsyslog-relp` images on head updates
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-build-images.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#1052 Fix target names for `shoot-rsyslog-relp` images
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-build-images.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#1056 Never initialize `logrus.StandardLogger().Formatter` in `main()` functions
  prow/cmd/branch-cleaner/main.go
  prow/cmd/image-builder/main.go
  prow/cmd/job-forker/main.go
  prow/cmd/milestone-activator/main.go
  prow/external-plugins/cherrypicker/main.go
  prow/external-plugins/cla-assistant/main.go
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#1061 Copy nginx:1.17.6 - used for registry-cache e2e tests
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1066 Prepare switch from GCR to Artifact-Registry
  config/images/README.md
  config/images/images.yaml
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/ci-infra/build-job-images.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/ci-infra/copy-images.yaml
  config/prow/autobump-config/prow-component-autobump-config.yaml
  config/prow/cluster/cherrypicker_deployment.yaml
  config/prow/cluster/cla_assistant_deployment.yaml
Labels: kind/technical-debt, size/M, approved, lgtm, cla: yes

#1067 Switch GCR to Artifact-Registry
  config/images/images.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-build-dev-images.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-check-vulnerabilities.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-test-builds.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-unit-tests.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
  config/jobs/gardener-extension-networking-calico/gardener-extension-networking-calico-unit-tests.yaml
  config/jobs/gardener-extension-networking-cilium/gardener-extension-networking-cilium-unit-tests.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-build-images.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-e2e-kind.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-test-builds.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-unit-tests.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-build-images.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-integration-tests.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-unit-tests.yaml
  config/jobs/gardener/gardener-apidiff.yaml
  config/jobs/gardener/gardener-branch-cleaner.yaml
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-release-handler.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-84.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-85.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-86.yaml
  images/krte/variants.yaml
Labels: kind/technical-debt, size/L, approved, lgtm, cla: yes

#1049 Add `verify` make target and use it `presubmit` and `periodic` jobs
  Makefile
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1069 Fix alertmanager template file location
  config/prow/cluster/monitoring/base-prow/alertmanager/config.yaml
  config/prow/cluster/monitoring/base-prow/kustomization.yaml
  config/prow/cluster/monitoring/base-prow/prometheusOperator-deployment-patch.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes
