Repository gardener/ci-infra, pull requests merged in 2023-09, with the labels that each got.

#872 Reduce user's permissions in branch-protection rules
  config/prow/config.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#874 Update `kubectl` image for deployer to `1.27.5`
  config/jobs/ci-infra/ci-infra-postsubmits.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#875 Enable dependabot for automatically updating `k8s.io/test-infra` dependency
  .github/dependabot.yaml
  .github/workflows/vendor_k8s_test_infra.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#886 Allow admins to bypass branch-protection rules for concourse managed repositories
  config/prow/config.yaml
Labels: kind/regression, size/XS, approved, lgtm, cla: yes

#887 Update golang test images
  images/golang-test/variants.yaml
  images/krte/variants.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#890 Build `gardenertools` image
  config/jobs/gardener/gardener-build-dev-images.yaml
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#891 Include binaries from `gardenertools` image into `golang-test` and `krte` images
  images/golang-test/Dockerfile
  images/golang-test/variants.yaml
  images/krte/Dockerfile
  images/krte/variants.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#892 Add `import-tools-bin` make target to tests
  config/jobs/gardener/gardener-apidiff.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-77.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-78.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-79.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#894 Trigger build of `gardenertools` image when `go.mod` is changing
  config/jobs/gardener/gardener-build-dev-images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#898 Reduce retention days and increase memory request for prometheus on build cluster
  config/prow/cluster/monitoring/build-cluster/prometheus.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#904 Update golang-test of `gardener/gardener-extension-networking-calico` tests to Go 1.21
  config/jobs/gardener-extension-networking-calico/gardener-extension-networking-calico-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#899 Reduce prow log level to `info`
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#900 Update `krte` image to `debian:bookworm`
  images/krte/Dockerfile
  images/krte/README.md
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#909 Set fixed debian version in test images
  images/golang-test/variants.yaml
  images/krte/Dockerfile
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#912 `branch-cleaner` removes branch protection rules of branches it plans to delete
  prow/cmd/branch-cleaner/README.md
  prow/cmd/branch-cleaner/branchcleaner.go
  prow/cmd/branch-cleaner/branchcleaner_test.go
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#915 Update golang-test of `gardener/gardener-extension-networking-cilium` tests to Go 1.21
  config/jobs/gardener-extension-networking-cilium/gardener-extension-networking-cilium-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#916 Update golang-test of `gardener/gardener-extension-shoot-networking-filter` tests to Go 1.21
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#917 Update golang-test of `gardener/gardener-extension-shoot-oidc-service` tests to Go 1.21
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes
