Repository gardener/ci-infra, pull requests merged in 2023-08, with the labels that each got.

#813 Enable dependabot to create update PRs for docker images
  .github/dependabot.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#814 Use dependabot compatible docker image format
  Dockerfile
  Makefile
  images/golang-test/Dockerfile
  images/golang-test/variants.yaml
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#825 Use `--force-conflicts` parameter in `deploy.sh`
  config/prow/deploy.sh
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#819 [image-builder] allow additional fields in `variants.yaml`
  prow/cmd/image-builder/buildcontroller.go
  prow/cmd/image-builder/buildcontroller_test.go
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#823 Adapt `high-availability` settings for prow cluster workloads
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/deck_service.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_service.yaml
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
  config/prow/cluster/monitoring/base-prow/alertmanager-alertmanager.yaml
  config/prow/cluster/monitoring/base-prow/alertmanager-service.yaml
  config/prow/cluster/monitoring/base-prow/kustomization.yaml
  config/prow/cluster/monitoring/base-prow/prometheus-service.yaml
  config/prow/cluster/monitoring/base-prow/prometheus.yaml
  config/prow/cluster/monitoring/base-prow/prometheusAdapter-deployment.yaml
  config/prow/cluster/monitoring/base-prow/prometheusAdapter-service.yaml
  config/prow/cluster/oauth2-proxy/helm/values.yaml
  config/prow/cluster/oauth2-proxy/kustomization.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy-deployment.yaml
  config/prow/cluster/oauth2-proxy/patch-oauth2-proxy-deployment.yaml
Labels: kind/enhancement, size/XL, approved, lgtm, cla: yes

#828 More `high-availability` settings for prow cluster workloads
  config/prow/cluster/gcsweb_deployment.yaml
  config/prow/cluster/gcsweb_service.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#820 Disable major and minor version updates for `golang-test` images by `dependabot`
  .github/dependabot.yaml
Labels: kind/bug, kind/enhancement, size/XS, approved, lgtm, cla: yes

#831 Fix `gcsweb` health and readiness endpoints and ports
  config/prow/cluster/gcsweb_deployment.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#836 Clean up the `bash` image for registry-cache. Add copy for `registry:2.82`. Add comments which images should no longer be maintained
  config/images/images.yaml
Labels: kind/cleanup, size/S, approved, lgtm, cla: yes

#835 Update `golang-test` images
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#837 Update `copy-images` tool
  .github/dependabot.yaml
  images/copy-images/Dockerfile
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#843 Update `golang-test` of `gardener/gardener` tests to `Go 1.21`
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#848 Build Gardener `krte` image
  config/jobs/ci-infra/build-job-images.yaml
  images/krte/Dockerfile
  images/krte/README.md
  images/krte/variants.yaml
  images/krte/wrapper.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#849 Fix path of `wrapper.sh` in `krte` Dockerfile
  images/krte/Dockerfile
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#851 Add `images/krte/wrapper.sh` as exception to dockerignore
  .dockerignore
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#852 Use Gardener `krte` image with Go 1.21 for e2e tests on master branch of `gardener/gardener`
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#854 Make `wrapper.sh` in krte image executable
  images/krte/wrapper.sh
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#857 Add prow jobs for gardener-extension-shoot-rsyslog-relp repo
  config/images/images.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-integration-tests.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-test-builds.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-unit-tests.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  config/testgrids/config.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#859 Update registry-cache unit tests job to go@1.21
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#862 Add tests for gardener-extension-shoot-networking-filter.
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-e2e-kind.yaml
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-unit-tests.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  config/testgrids/config.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#867 Add e2e test job for gardener-extension-shoot-rsyslog-relp repo
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-e2e-kind.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#847 Add e2e tests for registry-cache pull requests
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-e2e-kind.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes
