Repository gardener/ci-infra, pull requests merged in 2023-05, with the labels that each got.

#715 Stabilize prometheus in build cluster
  config/prow/cluster/monitoring/build-cluster/prometheus.yaml
  config/prow/cluster/monitoring/trusted-cluster/prometheus.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#719 Update to golang 1.19.9 & 1.20.4
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#721 Update to `gcr.io/kaniko-project/executor:v1.9.2`
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-test-builds.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-test-builds.yaml
  config/jobs/gardener/gardener-test-builds.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-68.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-69.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-70.yaml
  prow/cmd/image-builder/main.go
Labels: kind/bug, kind/enhancement, size/S, approved, lgtm, cla: yes

#718 Update to `ingress-nginx@v1.7.1`
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#720 Generate `oauth2-proxy` deployments from oauth2-proxy-6.12.0 helm chart
  config/prow/cluster/oauth2-proxy/helm/generate-oauth2-proxy-deployments.sh
  config/prow/cluster/oauth2-proxy/kustomization.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy-deployment.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#725 registry-cache-unit-tests: Use `make verify-extended` and reduce resouces
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes
