Repository gardener/ci-infra, pull requests merged in 2023-10, with the labels that each got.

#940 Add registry:2.8.3
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#932 Update `ingress-nginx` and `oauth2-proxy` in prow clusters
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy-deployment.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#936 Move build job of `golang-test` image from `gardener/ci-infra` to `gardener/gardener`
  config/jobs/ci-infra/build-job-images.yaml
  config/jobs/gardener/gardener-build-dev-images.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#937 Build `krte` image based on `golang-test` image
  .github/dependabot.yaml
  Dockerfile
  images/golang-test/Dockerfile
  images/golang-test/README.md
  images/golang-test/variants.yaml
  images/krte/Dockerfile
  images/krte/README.md
  images/krte/variants.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#948 Adds external plugins for shoot-rsyslog-relp extension
  config/prow/labels.yaml
  config/prow/plugins.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#950 Revendor to a version of `k8s.io/test-infra` where pushToNamedFork is implemented for the gitv2 client
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/config/inrepoconfig.go
  vendor/k8s.io/test-infra/prow/git/v2/fakes.go
  vendor/k8s.io/test-infra/prow/git/v2/publisher.go
  vendor/k8s.io/test-infra/prow/git/v2/remote.go
  vendor/modules.txt
Labels: kind/regression, size/L, approved, lgtm, cla: yes

#958 Update `ingress-nginx` to `v1.9.3`
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#960 Update golang-test of `gardener/gardener-extension-shoot-rsyslog-relp` tests to Go 1.21
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-integration-tests.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#944 Update `kaniko` to v1.16.0
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-test-builds.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-test-builds.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-test-builds.yaml
  config/jobs/gardener/gardener-test-builds.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-79.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-80.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-81.yaml
  prow/cmd/image-builder/main.go
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#966 Add PR author to release-notes of cherry-picked PRs
  prow/external-plugins/cherrypicker/server.go
  prow/external-plugins/cherrypicker/server_test.go
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#970 Add publish-test-images job to the registry-cache extension
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-test-builds.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#972 Remove `check-docforge`
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/cleanup, size/XS, approved, lgtm, cla: yes

#977 Build dev and test images of `gardener-node-agent`
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-test-builds.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#981 Stop building `gardener/gardener` dev-images in prow
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-test-builds.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-80.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-81.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-82.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#980 Update ingress-nginx to `v1.94` and enable annotation validations
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes
