Repository gardener/ci-infra, pull requests merged in 2023-03, with the labels that each got.

#621 Test shoot-oidc-service extension with go 1.20
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#626 Add job image to copy images from DockerHub to GCR
  config/jobs/ci-infra/build-golang-test-image.yaml
  config/jobs/ci-infra/build-job-images.yaml
  images/copy-images/Dockerfile
Labels: kind/enhancement, size/L, approved, ok-to-test, lgtm, cla: yes

#628 Remove image builder context for copy-images job, add dockerfile as arg
  config/jobs/ci-infra/build-job-images.yaml
Labels: kind/bug, size/M, approved, ok-to-test, lgtm, cla: yes

#629 Add target to Dockerfile
  images/copy-images/Dockerfile
Labels: kind/bug, size/XS, approved, ok-to-test, lgtm, cla: yes

#630 Add missing tagging schemes for building `copy-images` image
  config/jobs/ci-infra/build-job-images.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#613 Update to Go 1.19.7 & 1.20.2
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#623 Create docker configuration for dind to enable using nodes with cgroupv2
  config/prow/cluster/base/dind-docker-config_configmap.yaml
  config/prow/cluster/base/kustomization.yaml
  config/prow/config.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#633 Remove custom `daemon.json` from docker in docker preset
  config/prow/config.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#631 Added prow job to copy images
  config/images/README.md
  config/images/copy-images.sh
  config/images/images.yaml
  config/jobs/ci-infra/copy-images.yaml
Labels: kind/enhancement, size/L, approved, ok-to-test, lgtm, cla: yes

#635 Fix volumeMounts in copy-images prow job
  config/jobs/ci-infra/copy-images.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#638 Addedd kubernetesui/dashboard v2.2.0 to copy-images.yaml
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, ok-to-test, lgtm, cla: yes

#639 Increase timeout for periodic E2E test job `ci-gardener-e2e-kind-ha-multi-zone-upgrade-release-v1-65`
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-64.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-65.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-66.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#644 Add ScheererJ as maintainer
  OWNERS_ALIASES
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#646 Added images for other gardener repositories
  config/images/images.yaml
Labels: kind/enhancement, size/M, approved, ok-to-test, lgtm, cla: yes

#653 Update nginx to v1.7.0
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#649 Clean up copies for `openstack-cloud-controller-manager` and `cinder-csi-plugin`
  config/images/images.yaml
Labels: kind/cleanup, size/XS, approved, lgtm, cla: yes

#652 Github authentication for monitoring
  README.md
  config/prow/cluster/monitoring/build-cluster/grafana-ingress.yaml
  config/prow/cluster/monitoring/trusted-cluster/grafana-ingress.yaml
  config/prow/cluster/oauth2-proxy/config/oauth2_proxy.cfg
  config/prow/cluster/oauth2-proxy/helm/README.md
  config/prow/cluster/oauth2-proxy/helm/generate-oauth2-proxy-deployments.sh
  config/prow/cluster/oauth2-proxy/helm/values.yaml
  config/prow/cluster/oauth2-proxy/kustomization.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy-deployment.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy-namespace.yaml
  config/prow/deploy.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#658 Copy Fluent Operator images
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#661 Increase CPU limit for upgrade test job
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-65.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-66.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-67.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#662 Add label for IPCEI projects
  config/prow/labels.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#663 Enable tests and checks for extension-networking-calico repository
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/gardener/gardener-extension-networking-calico/gardener-extension-networking-calico-e2e-kind.yaml
  config/jobs/gardener/gardener-extension-networking-calico/gardener-extension-networking-calico-unit-tests.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  config/testgrids/config.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#665 Update alpine to 3.15.8
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes
