Repository gardener/ci-infra, pull requests merged in 2023-07, with the labels that each got.

#774 Update images.yaml
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#778 Use FQDN for `ghproxy` endpoint in prow jobs
  config/jobs/ci-infra/ci-infra-periodics.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#776 Introduce `release-handler`
  Dockerfile
  Makefile
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/gardener/gardener-release-handler.yaml
  go.mod
  go.sum
  prow/cmd/release-handler/README.md
  prow/cmd/release-handler/main.go
  prow/cmd/release-handler/release_handler_suite_test.go
  prow/cmd/release-handler/releasehandler.go
  prow/cmd/release-handler/releasehandler_test.go
  vendor/github.com/Masterminds/semver/.travis.yml
  vendor/github.com/Masterminds/semver/CHANGELOG.md
  vendor/github.com/Masterminds/semver/LICENSE.txt
  vendor/github.com/Masterminds/semver/Makefile
  vendor/github.com/Masterminds/semver/README.md
  vendor/github.com/Masterminds/semver/appveyor.yml
  vendor/github.com/Masterminds/semver/collection.go
  vendor/github.com/Masterminds/semver/constraints.go
  vendor/github.com/Masterminds/semver/doc.go
  vendor/github.com/Masterminds/semver/version.go
  vendor/github.com/Masterminds/semver/version_fuzz.go
  vendor/modules.txt
Labels: kind/enhancement, size/XXL, approved, lgtm, cla: yes

#779 Update to Go 1.19.11 and 1.20.6
  Dockerfile
  Makefile
  images/golang-test/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#780 Update to alpine 3.18.2
  Dockerfile
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#794 Set `retentionSize` to 90GB for prometheus instances
  config/prow/cluster/monitoring/base-prow/prometheus.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#795 Reduce the memory resource requests for the registry-cache builds
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-build-images.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-test-builds.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#797 Reduce the memory resource requests for the gardener/gardener builds
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-test-builds.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#800 Update registry-cache unit tests job to go@1.20
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#796 Reduce the memory resource requests for the dependency-watchdog builds
  config/jobs/dependency-watchdog/dependency-watchdog-build-dev-images.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-test-builds.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#806 Add envoyproxy v1.26.4
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#798 Added new prow job to run e2e tests of etcd-druid with feature gates turned on
  config/jobs/etcd-druid/druid-e2e-kind-alpha-features.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes
