Repository gardener/ci-infra, pull requests merged in 2024-01, with the labels that each got.

#1080 Added new prow job with feature gate turned off to run etcd-druid e2e tests with etcd-custom-image.
  config/jobs/etcd-druid/druid-e2e-kind-nondistroless-etcd.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1084 Route `KubePodNotReady` alert to `null-receiver`
  config/prow/cluster/monitoring/base-prow/alertmanager/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1086 Enable autobumping `gcsweb` again
  config/prow/cluster/gcsweb_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1090 Bump up container images: fluent-bit to v2.2.0 and fluent-operator to…
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1097 Update golang-test of `gardener/dependency-watchdog` to Go 1.21
  config/jobs/dependency-watchdog/dependency-watchdog-check-vulnerabilities.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#982 copy images from ghcr and public.ecr.aws for IPv6 support
  config/images/images.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1108 Fix `ulimit` error in `krte` image when starting docker service with docker-ce 25.0.0
  images/krte/Dockerfile
  images/krte/wrapper.sh
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#1121 Replace upstream `krte` images with gardener images
  config/jobs/dependency-watchdog/dependency-watchdog-e2e-kind.yaml
  config/jobs/etcd-druid/druid-e2e-kind-nondistroless-etcd.yaml
  config/jobs/etcd-druid/druid-e2e-kind.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-e2e-kind.yaml
  config/jobs/gardener-extension-networking-calico/gardener-extension-networking-calico-e2e-kind.yaml
  config/jobs/gardener-extension-networking-cilium/gardener-extension-networking-cilium-e2e-kind.yaml
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-e2e-kind.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-e2e-kind.yaml
  config/jobs/landscaper/landscaper-e2e-kind.yaml
Labels: kind/bug, size/M, approved, lgtm, cla: yes
