Repository gardener/ci-infra, pull requests merged in 2024-07, with the labels that each got.

#1953 Update go version for DWD `check-vul` job
  config/jobs/dependency-watchdog/dependency-watchdog-check-vulnerabilities.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1962 Follow up to renovate copy images configuration
  .github/renovate.json5
  config/images/images.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1966 Follow up to renovate copy images configuration [2]
  .github/renovate.json5
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1972 Follow up to renovate copy images configuration [3]
  .github/renovate.json5
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1978 Allow version suffixes in the container copy logic
  .github/renovate.json5
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2004 [renovate] Update helm to `v3.15.2` and golang to `1.22.5`
  .github/renovate.json5
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2006 Increase renovate-cache volume size to 20Gi
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2018 Use full image of `renovate`
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2038 Copy registry:3.0.0-beta.1
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2112 Correctly sort the version in branch cleaner
  prow/cmd/branch-cleaner/branchcleaner.go
  prow/cmd/branch-cleaner/branchcleaner_test.go
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#2115 Remove prometheus memory limit and VPA maxAllowed
  config/prow/cluster/monitoring/build-cluster/prometheus.yaml
  config/prow/cluster/monitoring/build-cluster/prometheus_vpa.yaml
  config/prow/cluster/monitoring/trusted-cluster/prometheus_vpa.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes
