Repository gardener/ci-infra, pull requests merged in 2024-11, with the labels that each got.

#2633 Fix test-integration target name
  config/jobs/cert-management/cert-management-integration-tests.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#2636 registry-cache: Increase the resource requests for the e2e tests
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-e2e-kind.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2637 Clean up test logs from `gardener-prow` GCS bucket
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/prow/cluster/kustomization.yaml
  config/prow/cluster/rclone_config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#2642 renovate: ignore status checks for automerging
  .github/renovate.json5
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#2643 Extract renovate `automerge-with-tide` preset
  .github/renovate.json5
  README.md
  config/renovate/README.md
  config/renovate/automerge-with-tide.json5
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#2644 Add more shared renovate config presets
  .github/renovate.json5
  config/renovate/README.md
  config/renovate/automerge-with-tide.json5
  config/renovate/imagevector.json5
  config/renovate/makefile-versions.json5
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#2654 Revert "Clean up test logs from gardener-prow GCS bucket (#2637)"
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/prow/cluster/kustomization.yaml
  config/prow/cluster/rclone_config.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes

#2661 Copy registry:3.0.0-rc.1
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2649 [renovate] Do not install `helm` and `go` in `postUpgradeTasks`
  .github/renovate.json5
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2666 Clean up test logs from gardener-prow GCS bucket
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/prow/cluster/kustomization.yaml
  config/prow/cluster/rclone_config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#2679 Increase timeouts of `*-gardener-e2e-kind` and `*-gardener-e2e-kind-ipv6` to 1h15min
  config/jobs/gardener/gardener-e2e-kind-ipv6.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2678 Added prow job configurations for unit-tests, integration-tests, dev and test image builds
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-build-dev-images.yaml
  config/jobs/etcd-druid/etcd-druid-e2e-kind-nondistroless-etcd.yaml
  config/jobs/etcd-druid/etcd-druid-e2e-kind.yaml
  config/jobs/etcd-druid/etcd-druid-integration-tests.yaml
  config/jobs/etcd-druid/etcd-druid-test-builds.yaml
  config/jobs/etcd-druid/etcd-druid-unit-tests.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#2687 Corrected krte image and skip release regex pattern for etcd-druid jobs
  config/jobs/etcd-druid/etcd-druid-e2e-kind-nondistroless-etcd.yaml
  config/jobs/etcd-druid/etcd-druid-e2e-kind.yaml
  config/jobs/etcd-druid/etcd-druid-integration-tests.yaml
  config/jobs/etcd-druid/etcd-druid-test-builds.yaml
  config/jobs/etcd-druid/etcd-druid-unit-tests.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#2717 Don't protect branches created by dependatbot or renovate
  config/prow/config.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#2759 Update go to 1.23 for DWD
  config/jobs/dependency-watchdog/dependency-watchdog-check-vulnerabilities.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-e2e-kind.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-unit-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#2757 Remove etcd-druid nondistroless prow job
  config/jobs/etcd-druid/etcd-druid-e2e-kind-nondistroless-etcd.yaml
Labels: kind/cleanup, size/M, approved, lgtm, cla: yes
