Repository gardener/ci-infra, pull requests merged in 2024-10, with the labels that each got.

#2464 Change locations of prow images
  config/jobs/ci-infra/ci-infra-automate-testgrid.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/mkpj.sh
  config/prow/autobump-config/prow-component-autobump-config.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/gcsweb_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/needs-rebase_deployment.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
  hack/bootstrap-config.sh
  hack/check-config.sh
  hack/check-testgrid-config.sh
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#2466 Activate `overwrite-pending-contexts` feature for `tide`
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2507 Increase memory requests/limits for gardener/gardener unit tests
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2609 Allow `skip-review` label on all tide-enabled repos
  config/prow/config.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#2610 Add renovate presubmit job to all enabled repos
  README.md
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/common/renovate-presubmits.yaml
  config/jobs/gardener/gardener-check-renovate-config.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#2616 renovate: use automerge comment
  .github/renovate.json5
  config/prow/plugins.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes
