Repository gardener/ci-infra, pull requests merged in 2024-03, with the labels that each got.

#1282 Copy alpine:3.19.1
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1274 Enable renovate for UI and CLI repositories
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1266 Add v2.7.0 image of aws load balancer controller
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, ok-to-test, lgtm, cla: yes

#1291 Do not run multiple `renovate` jobs in parallel
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1295 Harmonize `GOPROXY` settings
  config/jobs/ci-infra/build-ci-infra-images.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/gardener/gardener-build-dev-images.yaml
  config/jobs/gardener/gardener-test-builds.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-87.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-88.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-89.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-90.yaml
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
  config/prow/config.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1300 update golang test images for calico and cilium
  config/jobs/gardener-extension-networking-calico/gardener-extension-networking-calico-e2e-kind.yaml
  config/jobs/gardener-extension-networking-calico/gardener-extension-networking-calico-unit-tests.yaml
  config/jobs/gardener-extension-networking-cilium/gardener-extension-networking-cilium-e2e-kind.yaml
  config/jobs/gardener-extension-networking-cilium/gardener-extension-networking-cilium-unit-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1307 Increase volume size of `renovate`
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/bug, approved, lgtm, cla: yes

#1345 Copy new tags for the observability images
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1352 Enable renovate for diki
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1368 Copy envoy proxy v1.29.2.
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1390 Enable renovate for gardener/ops-toolbelt
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1394 Update AWS ebs-csi-driver image in copy-list
  config/images/images.yaml
Labels: kind/task, size/XS, approved, lgtm, cla: yes
