Repository gardener/ci-infra, pull requests merged in 2024-06, with the labels that each got.

#1828 Copy `envoyproxy/envoy-distroless@v1.30.2` image
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1814 Add e2e test for `kind-operator-seed-up` make target in `gardener/gardener` repository
  config/jobs/gardener/gardener-e2e-kind-operator-seed.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#1880 Copy new tags for the observability images
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1890 Enable Static Application Security Testing (SAST) in Gardener unit tests
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1895 chore/update fluent bit
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1900 fix fluent-operator source
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1924 Apply latest upstream changes to `wrapper.sh`
  images/krte/wrapper.sh
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1939 Copy envoy v1.30.3 image
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1930 Add gardener-cert-management repo to prow configs
  config/jobs/cert-management/cert-management-e2e-kind.yaml
  config/jobs/cert-management/cert-management-unit-tests.yaml
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
  config/prow/config.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  config/testgrids/config.yaml
  prow/cmd/milestone-activator/activator_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, cla: yes
