Repository gardener/ci-infra, pull requests merged in 2024-02, with the labels that each got.

#1126 Bump up fluent-bit container image to v2.2.2
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1128 Copy registry:3.0.0-alpha.1
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1140 Build an `krte` image which uses `Go 1.22`
  images/krte/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1148 Update registry-cache jobs to go@1.22
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-e2e-kind.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1123 Optimize resource utilization in prow clusters by adding resource requests and enabling `VPA`
  config/prow/cluster/athens/athens_deployment.yaml
  config/prow/cluster/athens/athens_vpa.yaml
  config/prow/cluster/athens/helm/values.yaml
  config/prow/cluster/athens/kustomization.yaml
  config/prow/cluster/bootstrap-trusted/trusted_serviceaccounts.yaml
  config/prow/cluster/cherrypicker_deployment.yaml
  config/prow/cluster/cherrypicker_vpa.yaml
  config/prow/cluster/cla_assistant_deployment.yaml
  config/prow/cluster/cla_assistant_vpa.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_vpa.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/deck_vpa.yaml
  config/prow/cluster/gcsweb_deployment.yaml
  config/prow/cluster/gcsweb_vpa.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/ghproxy_vpa.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_vpa.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/horologium_vpa.yaml
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx_vpa.yaml
  config/prow/cluster/ingress-nginx/kustomization.yaml
  config/prow/cluster/kustomization.yaml
  config/prow/cluster/monitoring/build-cluster/kustomization.yaml
  config/prow/cluster/monitoring/build-cluster/prometheus.yaml
  config/prow/cluster/monitoring/build-cluster/prometheus_vpa.yaml
  config/prow/cluster/monitoring/trusted-cluster/kustomization.yaml
  config/prow/cluster/monitoring/trusted-cluster/prometheus.yaml
  config/prow/cluster/monitoring/trusted-cluster/prometheus_vpa.yaml
  config/prow/cluster/needs-rebase_deployment.yaml
  config/prow/cluster/needs-rebase_vpa.yaml
  config/prow/cluster/oauth2-proxy/helm/values.yaml
  config/prow/cluster/oauth2-proxy/kustomization.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy-deployment.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy_vpa.yaml
  config/prow/cluster/prow_controller_manager_deployment.yaml
  config/prow/cluster/prow_controller_manager_vpa.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/sinker_vpa.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/statusreconciler_vpa.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/cluster/tide_vpa.yaml
Labels: kind/enhancement, size/XL, approved, lgtm, cla: yes

#1146 Use registry-cache when running build verify prow jobs
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-test-builds.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-test-builds.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-test-builds.yaml
  config/jobs/gardener/gardener-test-builds.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-86.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-87.yaml
  config/jobs/gardener/releases/gardener-gardener-release-v1-88.yaml
  prow/cmd/image-builder/main.go
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#1156 Update `gardener` periodic prow jobs to `go@1.22`
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1157 Remove Go 1.20 version of `krte` image
  images/krte/variants.yaml
Labels: kind/cleanup, size/XS, approved, lgtm, cla: yes

#1163 Introduce `renovate` bot 🤖
  .github/dependabot.yaml
  .github/renovate.json5
  Makefile
  README.md
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/prow/cluster/athens/helm/generate-athens-deployments.sh
  config/prow/cluster/bootstrap-trusted/trusted_serviceaccounts.yaml
  config/prow/cluster/ingress-nginx/helm/generate-ingress-nginx-deployments.sh
  config/prow/cluster/monitoring/base/update.sh
  config/prow/cluster/oauth2-proxy/helm/generate-oauth2-proxy-deployments.sh
  config/prow/cluster/renovate/helm/README.md
  config/prow/cluster/renovate/helm/generate-renovate-deployments.sh
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/kustomization.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
  config/prow/cluster/renovate/renovate_namespace.yaml
  config/prow/deploy.sh
  hack/tools.mk
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#1181 Update Go toolchain to `1.22.0`
  go.mod
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1187 Remove workaround for wrong scope in `oauth2-proxy`
  config/prow/cluster/oauth2-proxy/helm/values.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy-deployment.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#1177 Run `renovate` every 5 minutes
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1184 Validate `renovate` config in PRs in `gardener/gardener`
  config/jobs/gardener/gardener-check-renovate-config.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1210 Use `config:recommended` instead of `config:best-practices` in renovate config
  .github/renovate.json5
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1202 Enable `tide` and some other plugins for `gardener-extension-shoot-rsyslog`
  config/jobs/common/issue-pr-lifecycle.yaml
  config/prow/config.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  prow/cmd/milestone-activator/activator_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, cla: yes

#1218 Add envoy-v1.26.7
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1226 Change test image to golang 1.22 for network-filter.
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-e2e-kind.yaml
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes
