Repository gardener/ci-infra, pull requests merged in 2024-12, with the labels that each got.

#2807 Add a prometheus instance for collecting performance metrics
  config/prow/cluster/coredns/coredns-custom-config.yaml
  config/prow/cluster/coredns/kustomization.yaml
  config/prow/cluster/monitoring/base-prow/grafana-deployment.yaml
  config/prow/cluster/monitoring/build-cluster/grafana-datasources.yaml
  config/prow/cluster/monitoring/build-cluster/kustomization.yaml
  config/prow/cluster/monitoring/build-cluster/prometheus-performance.yaml
  config/prow/deploy.sh
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#2812 Add initial flux deployment
  clusters/base/flux-system/gotk-components.yaml
  clusters/base/flux-system/gotk-sync.yaml
  clusters/base/flux-system/kustomization.yaml
  clusters/prow-build/flux-system/kustomization.yaml
  clusters/prow-build/flux-system/patch-kustomization.yaml
  clusters/prow-build/kustomization.yaml
  clusters/prow-trusted/flux-system/kustomization.yaml
  clusters/prow-trusted/flux-system/patch-kustomization.yaml
  clusters/prow-trusted/kustomization.yaml
Labels: kind/enhancement, size/XXL, approved, lgtm, cla: yes

#2813 Deploy `test-pods` namespace and its content via `flux`
  clusters/base/test-pods-kustomization.yaml
  config/prow/cluster/base/kustomization.yaml
  deploy/test-pods/cpu-limit-range_limitrange.yaml
  deploy/test-pods/dind-docker-config_configmap.yaml
  deploy/test-pods/kustomization.yaml
  deploy/test-pods/mem-limit-range_limitrange.yaml
  deploy/test-pods/test-pods_namespace.yaml
  deploy/test-pods/test-pods_pod-disruption-budget.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#2816 Skip unneeded presubmit jobs on flux changes
  config/jobs/ci-infra/ci-infra-presubmits.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2817 Deploy storageclass via flux
  clusters/base/kustomization.yaml
  clusters/base/storageclass-kustomization.yaml
  config/prow/cluster/kustomization.yaml
  config/prow/deploy.sh
  deploy/storageclass/gce-ssd_storageclass.yaml
  deploy/storageclass/kustomization.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#2818 Skip unneeded postsubmit jobs on flux changes
  config/jobs/ci-infra/build-ci-infra-images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2828 Migrate renovate deployment to flux
  .github/renovate.json5
  clusters/prow-trusted/kustomization.yaml
  clusters/prow-trusted/renovate-kustomization.yaml
  config/prow/cluster/renovate/helm/README.md
  config/prow/cluster/renovate/helm/generate-renovate-deployments.sh
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
  config/prow/cluster/renovate/renovate_namespace.yaml
  config/prow/deploy.sh
  deploy/renovate/kustomization.yaml
  deploy/renovate/renovate-helmrepo.yaml
  deploy/renovate/renovate.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#2830 Migrate `prow` component deployment to `flux`
  clusters/prow-trusted/kustomization.yaml
  clusters/prow-trusted/prow-kustomization.yaml
  config/prow/cluster/prowjob_customresourcedefinition.yaml
  config/prow/deploy.sh
  deploy/prow/builder_serviceaccount.yaml
  deploy/prow/cherrypicker_deployment.yaml
  deploy/prow/cherrypicker_service.yaml
  deploy/prow/cherrypicker_vpa.yaml
  deploy/prow/cla_assistant_deployment.yaml
  deploy/prow/cla_assistant_service.yaml
  deploy/prow/cla_assistant_vpa.yaml
  deploy/prow/crier_deployment.yaml
  deploy/prow/crier_rbac.yaml
  deploy/prow/crier_service.yaml
  deploy/prow/crier_vpa.yaml
  deploy/prow/deck_deployment.yaml
  deploy/prow/deck_rbac.yaml
  deploy/prow/deck_service.yaml
  deploy/prow/deck_vpa.yaml
  deploy/prow/gcsweb_deployment.yaml
  deploy/prow/gcsweb_ingress.yaml
  deploy/prow/gcsweb_namespace.yaml
  deploy/prow/gcsweb_service.yaml
  deploy/prow/gcsweb_vpa.yaml
  deploy/prow/ghproxy_deployment.yaml
  deploy/prow/ghproxy_pvc.yaml
  deploy/prow/ghproxy_service.yaml
  deploy/prow/ghproxy_vpa.yaml
  deploy/prow/hook_deployment.yaml
  deploy/prow/hook_rbac.yaml
  deploy/prow/hook_service.yaml
  deploy/prow/hook_vpa.yaml
  deploy/prow/horologium_deployment.yaml
  deploy/prow/horologium_rbac.yaml
  deploy/prow/horologium_service.yaml
  deploy/prow/horologium_vpa.yaml
  deploy/prow/kustomization.yaml
  deploy/prow/needs-rebase_deployment.yaml
  deploy/prow/needs-rebase_service.yaml
  deploy/prow/needs-rebase_vpa.yaml
  deploy/prow/prow_controller_manager_deployment.yaml
  deploy/prow/prow_controller_manager_rbac.yaml
  deploy/prow/prow_controller_manager_service.yaml
  deploy/prow/prow_controller_manager_vpa.yaml
  deploy/prow/prow_ingress.yaml
  deploy/prow/prow_namespace.yaml
  deploy/prow/rclone_config.yaml
  deploy/prow/sinker_deployment.yaml
  deploy/prow/sinker_rbac.yaml
  deploy/prow/sinker_service.yaml
  deploy/prow/sinker_vpa.yaml
  deploy/prow/statusreconciler_deployment.yaml
  deploy/prow/statusreconciler_rbac.yaml
  deploy/prow/statusreconciler_vpa.yaml
  deploy/prow/tide_deployment.yaml
  deploy/prow/tide_rbac.yaml
  deploy/prow/tide_service.yaml
  deploy/prow/tide_vpa.yaml
Labels: kind/enhancement, size/XXL, approved, lgtm, cla: yes

#2835 Move `coredns` custom config to `flux`
  clusters/prow-build/coredns-kustomization.yaml
  clusters/prow-build/kustomization.yaml
  config/prow/deploy.sh
  deploy/coredns/coredns-custom-config.yaml
  deploy/coredns/kustomization.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#2836 Fix `athens` deployment in `flux`
  deploy/athens/kustomization.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#2838 More fixes for `athens` deployment in `flux`
  deploy/athens/athens.yaml
  deploy/athens/kustomization.yaml
  deploy/athens/patch-athens-proxy.yaml
Labels: kind/bug, size/M, approved, lgtm, cla: yes

#2839 More more fixes for `athens` deployment in `flux`
  deploy/athens/athens-namespace.yaml
  deploy/athens/athens-prometheus-rbac.yaml
  deploy/athens/athens-vpa.yaml
  deploy/athens/kustomization.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#2833 Migrate `ingress-nginx` deployment to `flux`
  .github/renovate.json5
  clusters/base/ingress-nginx-kustomization.yaml
  clusters/base/kustomization.yaml
  config/prow/cluster/ingress-nginx/helm/README.md
  config/prow/cluster/ingress-nginx/helm/generate-ingress-nginx-deployments.sh
  config/prow/cluster/ingress-nginx/helm/values.yaml
  config/prow/cluster/ingress-nginx/ingress-nginx-deployment.yaml
  config/prow/cluster/ingress-nginx/kustomization.yaml
  config/prow/cluster/ingress-nginx/patch-ingress-nginx-admission-create.yaml
  config/prow/cluster/ingress-nginx/patch-ingress-nginx-admission-patch.yaml
  config/prow/deploy.sh
  deploy/ingress-nginx/ingress-nginx-helmrepo.yaml
  deploy/ingress-nginx/ingress-nginx-namespace.yaml
  deploy/ingress-nginx/ingress-nginx-vpa.yaml
  deploy/ingress-nginx/ingress-nginx.yaml
  deploy/ingress-nginx/kustomization.yaml
Labels: kind/enhancement, size/XXL, approved, lgtm, cla: yes

#2840 Fix athens deployment
  deploy/athens/athens.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#2834 Migrate `oauth2-proxy` deployment to `flux`
  .github/renovate.json5
  clusters/prow-trusted/kustomization.yaml
  clusters/prow-trusted/oauth2-proxy-kustomization.yaml
  config/prow/cluster/oauth2-proxy/helm/README.md
  config/prow/cluster/oauth2-proxy/helm/generate-oauth2-proxy-deployments.sh
  config/prow/cluster/oauth2-proxy/helm/values.yaml
  config/prow/cluster/oauth2-proxy/oauth2-proxy-deployment.yaml
  config/prow/cluster/oauth2-proxy/patch-oauth2-proxy-deployment.yaml
  config/prow/deploy.sh
  deploy/oauth2-proxy/config/oauth2_proxy.cfg
  deploy/oauth2-proxy/kustomization.yaml
  deploy/oauth2-proxy/oauth2-proxy-helmrepo.yaml
  deploy/oauth2-proxy/oauth2-proxy-namespace.yaml
  deploy/oauth2-proxy/oauth2-proxy-vpa.yaml
  deploy/oauth2-proxy/oauth2-proxy.yaml
Labels: kind/enhancement, size/XL, approved, lgtm, cla: yes

#2842 Migrate `oauth2-proxy` config to flux `HelmRelease`
  deploy/oauth2-proxy/config/oauth2_proxy.cfg
  deploy/oauth2-proxy/kustomization.yaml
  deploy/oauth2-proxy/oauth2-proxy.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#2853 chore: Add marc1404 to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2827 [GEP-28] Add job for `gardener-e2e-kind-gardenadm`
  config/jobs/gardener/gardener-e2e-kind-gardenadm.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#2916 Copy registry:3.0.0-rc.2
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes
