Repository gardener/ci-infra, pull requests merged in 2024-04, with the labels that each got.

#1443 Copy `envoyproxy/envoy-distroless@v1.29.3` image to `europe-docker.pkg.dev`
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1450 Enable renovate for landscaper-service and -cli repositories
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1452 Increase volume size of `renovate` cache `pvc`
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1467 Update location of `prow` go dependencies
  .github/renovate.json5
  go.mod
  go.sum
  prow/cmd/branch-cleaner/branchcleaner.go
  prow/cmd/branch-cleaner/branchcleaner_test.go
  prow/cmd/branch-cleaner/main.go
  prow/cmd/image-builder/buildcontroller.go
  prow/cmd/image-builder/buildcontroller_test.go
  prow/cmd/image-builder/main.go
  prow/cmd/job-forker/forking.go
  prow/cmd/job-forker/forking_test.go
  prow/cmd/job-forker/main.go
  prow/cmd/milestone-activator/activator.go
  prow/cmd/milestone-activator/activator_test.go
  prow/cmd/milestone-activator/main.go
  prow/cmd/release-handler/main.go
  prow/cmd/release-handler/releasehandler.go
  prow/cmd/release-handler/releasehandler_test.go
  prow/external-plugins/cherrypicker/main.go
  prow/external-plugins/cherrypicker/server.go
  prow/external-plugins/cherrypicker/server_test.go
  prow/external-plugins/cla-assistant/main.go
  prow/external-plugins/cla-assistant/plugin.go
  prow/external-plugins/cla-assistant/plugin_test.go
  prow/external-plugins/cla-assistant/server.go
  prow/external-plugins/cla-assistant/server_test.go
  prow/pkg/git/fakegit/fakegitclient.go
  prow/pkg/github/fakegithub/fakegithubclient.go
  prow/pkg/githubinteractor/github.go
  prow/pkg/githubinteractor/github_test.go
Labels: kind/cleanup, size/L, approved, lgtm, cla: yes

#1471 Fix `consistentImageExceptions` in `autobump-config`
  config/prow/autobump-config/prow-component-autobump-config.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes

#1521 Update go version for DWD jobs
  config/jobs/dependency-watchdog/dependency-watchdog-check-vulnerabilities.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-e2e-kind.yaml
  config/jobs/dependency-watchdog/dependency-watchdog-unit-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1527 Add envoyproxy/envoy-distroless v1.30.1
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1561 Add gardener-discovery-server repo to prow configs
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/jobs/gardener-discovery-server/gardener-discovery-server-test-builds.yaml
  config/jobs/gardener-discovery-server/gardener-discovery-server-unit-tests.yaml
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
  config/prow/config.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  config/testgrids/config.yaml
  prow/cmd/milestone-activator/activator_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, cla: yes

#1564 Build `gardener-discovery-server` image post submit
  config/jobs/gardener-discovery-server/gardener-discovery-server-build-images.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#1565 Skip building `ci-infra` images when there are changes in `images` folder only
  config/jobs/ci-infra/build-ci-infra-images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes
