Repository gardener/ci-infra, pull requests merged in 2024-05, with the labels that each got.

#1610 Remote `test-prometheus` rule from `gardener/gardener` unit tests
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1623 Add IPv6-only end-to-end tests to gardener/gardener.
  config/jobs/gardener/gardener-e2e-kind-ipv6.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#1711 Add e2e test jobs for gardener-discovery-server
  config/jobs/gardener-discovery-server/gardener-discovery-server-e2e-kind.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#1732 Update `plutono` and `vali{tail}` images
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#1741 Add `ipcei/oidc` and `ipcei/workload-identity` label for gardener repo
  config/prow/labels.yaml
  config/prow/plugins.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#1755 Decrease size of renovate cache volume to 10 GB
  config/prow/cluster/renovate/helm/values.yaml
  config/prow/cluster/renovate/renovate_deployment.yaml
Labels: kind/enhancement, approved, lgtm, cla: yes

#1773 Add `PodDisruptionBudget` for prow test pods
  config/prow/cluster/base/kustomization.yaml
  config/prow/cluster/base/test-pods_pod-disruption-budget.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes
