Repository gardener/ci-infra, pull requests merged in 2025-07, with the labels that each got.

#4054 Trust `gardener-github-actions` github app in networking extension repositories
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#4065 ci: Replace Concourse with GHA in status checks of DNS-/cert-management
  config/prow/config.yaml
Labels: kind/cleanup, size/S, approved, lgtm, cla: yes

#4084 Deactivate `branchprotector`
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/prow/config.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes

#4209 Adding hyperkube to the list of watched repos
  deploy/renovate/renovate.yaml
Labels: kind/task, size/XS, approved, lgtm, cla: yes
