Repository gardener/ci-infra, pull requests merged in 2025-02, with the labels that each got.

#3136 Removed check-generate from etcd-druid-unit-tests.yaml
  config/jobs/etcd-druid/etcd-druid-unit-tests.yaml
Labels: kind/enhancement, kind/task, size/XS, approved, lgtm, cla: yes

#3142 Revert "Bumping Prow and Prow - test-infra and Prow - ci-infra (#3134)"
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
  config/mkpj.sh
  config/prow/config.yaml
  deploy/prow/crier_deployment.yaml
  deploy/prow/deck_deployment.yaml
  deploy/prow/ghproxy_deployment.yaml
  deploy/prow/hook_deployment.yaml
  deploy/prow/horologium_deployment.yaml
  deploy/prow/needs-rebase_deployment.yaml
  deploy/prow/prow_controller_manager_deployment.yaml
  deploy/prow/sinker_deployment.yaml
  deploy/prow/statusreconciler_deployment.yaml
  deploy/prow/tide_deployment.yaml
  hack/bootstrap-config.sh
  hack/check-config.sh
Labels: kind/regression, size/M, approved, lgtm, cla: yes

#3163 New prow job for etcd-druid API go module
  config/jobs/etcd-druid/etcd-druid-api-unit-tests.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#3179 Fix required_status_checks for cert-management
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3199 Use `golang-test:1.24` for `ci-infra` unit tests
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/ci-infra/ci-infra-presubmits.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3203 Copy registry:3.0.0-rc.3
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3207 Use Go 1.24 for testing `gardener/gardener`
  config/jobs/gardener/gardener-e2e-kind-gardenadm.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ipv6.yaml
  config/jobs/gardener/gardener-e2e-kind-migration-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-operator-seed.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#3224 Update ghcr.io/fluent/fluent-operator/fluent-bit Docker tag to v3.2.5
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3234 Update registry-cache jobs to go@1.24
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-e2e-kind.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3237 Add fallbacks for gardener tests manipulating /etc/hosts.
  deploy/coredns/coredns-custom-config.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#3239 Increase timeout to `2h` for Gardener e2e tests
  config/jobs/gardener/gardener-e2e-kind-gardenadm.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ipv6.yaml
  config/jobs/gardener/gardener-e2e-kind-migration-ha-single-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-operator-seed.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
Labels: kind/flake, size/S, approved, lgtm, cla: yes

#3241 Add LucaBernstein to the OWNER_ALIASES
  OWNERS_ALIASES
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3250 Add `runc@v1.24` into `krte` image
  images/krte/Dockerfile
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3275 Highlight `[TIMEDOUT]` in build log
  config/prow/config.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3276 registry-cache: Increase the e2e tests timeout from 60m to 1h10m
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-e2e-kind.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#3202 Update shoot-rsyslog-relp jobs to go@1.24
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-e2e-kind.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-integration-tests.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-unit-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes
