Repository gardener/ci-infra, pull requests merged in 2025-08, with the labels that each got.

#4153 registry-cache: Increase the memory requests and limits for the unit tests
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#4321 chore: Mirror tag `v1.35.1` for `envoy-proxy/envoy-distroless`
  config/images/images.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#4332 ci: Maintain `krte` image variants (removed 1.23, added 1.25)
  images/krte/variants.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#4338 ci: Use Go 1.25 for testing `gardener/gardener`
  config/jobs/gardener/gardener-e2e-kind-gardenadm.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-node-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-node.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind-ha-multi-zone.yaml
  config/jobs/gardener/gardener-e2e-kind-ipv6.yaml
  config/jobs/gardener/gardener-e2e-kind-migration-ha-multi-node.yaml
  config/jobs/gardener/gardener-e2e-kind-migration.yaml
  config/jobs/gardener/gardener-e2e-kind-operator-seed.yaml
  config/jobs/gardener/gardener-e2e-kind-operator.yaml
  config/jobs/gardener/gardener-e2e-kind-upgrade.yaml
  config/jobs/gardener/gardener-e2e-kind.yaml
  config/jobs/gardener/gardener-integration-tests.yaml
  config/jobs/gardener/gardener-unit-tests.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#4344 Add missing `import-tools-bin` target to tests
  config/jobs/cert-management/cert-management-e2e-kind.yaml
  config/jobs/cert-management/cert-management-integration-tests.yaml
  config/jobs/cert-management/cert-management-unit-tests.yaml
  config/jobs/cluster-api-provider-gardener/cluster-api-provider-gardener-e2e-kind.yaml
  config/jobs/cluster-api-provider-gardener/cluster-api-provider-gardener-unit-tests.yaml
  config/jobs/extension-shoot-cert-service/extension-shoot-cert-service-e2e-kind.yaml
  config/jobs/extension-shoot-cert-service/extension-shoot-cert-service-unit-tests.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-e2e-kind.yaml
  config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-unit-tests.yaml
  config/jobs/external-dns-management/external-dns-management-integration-tests.yaml
  config/jobs/external-dns-management/external-dns-management-unit-tests.yaml
  config/jobs/gardener-discovery-server/gardener-discovery-server-e2e-kind.yaml
  config/jobs/gardener-discovery-server/gardener-discovery-server-unit-tests.yaml
  config/jobs/gardener-extension-image-rewriter/gardener-extension-image-rewriter-unit-tests.yaml
  config/jobs/gardener-extension-networking-calico/gardener-extension-networking-calico-e2e-kind.yaml
  config/jobs/gardener-extension-networking-calico/gardener-extension-networking-calico-unit-tests.yaml
  config/jobs/gardener-extension-networking-cilium/gardener-extension-networking-cilium-e2e-kind.yaml
  config/jobs/gardener-extension-networking-cilium/gardener-extension-networking-cilium-unit-tests.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-e2e-kind.yaml
  config/jobs/gardener-extension-registry-cache/gardener-extension-registry-cache-unit-tests.yaml
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-e2e-kind.yaml
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-e2e-operator.yaml
  config/jobs/gardener-extension-shoot-networking-filter/gardener-extension-shoot-networking-filter-unit-tests.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-e2e-kind.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-integration-tests.yaml
  config/jobs/gardener-extension-shoot-rsyslog-relp/gardener-extension-shoot-rsyslog-relp-unit-tests.yaml
Labels: area/cost, kind/enhancement, size/M, approved, lgtm, cla: yes
