Repository gardener/ci-infra, pull requests merged in 2025-01, with the labels that each got.

#2930 Enable Static Application Security Testing (SAST) in dependency-watchdog unit tests
  config/jobs/dependency-watchdog/dependency-watchdog-unit-tests.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#2987 Update tide merge label priority
  config/prow/config.yaml
Labels: kind/cleanup, size/XS, approved, lgtm, cla: yes

#3001 Drop `post-ci-infra-deploy-prow` prow job
  config/jobs/ci-infra/ci-infra-postsubmits.yaml
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#3015 Schedule prow jobs on nodes labeled with `prow.k8s.io/jobs-allowed="true"` only
  config/prow/config.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#3022 pull-gardener-apidiff: Update the go version
  config/jobs/gardener/gardener-apidiff.yaml
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#3002 Add tobschli to reviewers and approvers
  OWNERS_ALIASES
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#3090 Move deployment of `webserver-static-files` back to `plugins.yaml`
  config/prow/plugins.yaml
  config/prow/webserver-static-files/gardener-favicon.png
  config/prow/webserver-static-files/gardener-large.png
  config/prow/webserver-static-files/gardener.svg
  deploy/prow/kustomization.yaml
Labels: kind/bug, size/S, approved, lgtm, cla: yes
