Repository gardener/ci-infra, pull requests merged in 2025-09, with the labels that each got.

#4370 chore: Improve PR template
  .github/pull_request_template.md
Labels: kind/enhancement, size/XS, approved, lgtm, cla: yes

#4408 Support `distroless-v<version>` versioning scheme for envoy
  .github/renovate.json5
Labels: kind/enhancement, size/M, approved, lgtm, cla: yes

#4478 ci: Use Go 1.25 for certificate and DNS Prow jobs
  config/jobs/cert-management/cert-management-e2e-kind.yaml
  config/jobs/cert-management/cert-management-integration-tests.yaml
  config/jobs/cert-management/cert-management-unit-tests.yaml
  config/jobs/extension-shoot-cert-service/extension-shoot-cert-service-e2e-kind.yaml
  config/jobs/extension-shoot-cert-service/extension-shoot-cert-service-unit-tests.yaml
  config/jobs/external-dns-management/external-dns-management-integration-tests.yaml
  config/jobs/external-dns-management/external-dns-management-unit-tests.yaml
Labels: kind/enhancement, size/S, approved, lgtm, cla: yes

#4544 Fix copy-images.sh to be sh compatible
  config/images/copy-images.sh
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#4534 Add `gardener-extension-shoot-dns-service` repo to prow configs
  config/jobs/ci-infra/ci-infra-periodics.yaml
  config/jobs/common/issue-pr-lifecycle.yaml
  config/jobs/common/renovate-presubmits.yaml
  config/jobs/extension-shoot-dns-service/extension-shoot-dns-service-unit-tests.yaml
  config/prow/config.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  config/testgrids/config.yaml
  deploy/renovate/renovate.yaml
Labels: kind/enhancement, size/L, approved, lgtm, cla: yes
